<?php

namespace ContainerBxCUOYM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPricingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PricingController' shared autowired service.
     *
     * @return \App\Controller\PricingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PricingController.php';

        $container->services['App\\Controller\\PricingController'] = $instance = new \App\Controller\PricingController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\PricingController', $container));

        return $instance;
    }
}
